[project]
name = "hdf5io"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "future>=0.18.2",
    "numpy>=1.21.5",
    "pytest>=6.2.4",
    "setuptools>=58.0.4",
    "tables>=3.7.0",
    "zc-lockfile>=3.0.post1",
]
